services:
  database:
    image: postgres:18-trixie
    restart: always
    networks:
      - transcendance
    env_file:
      - ./srcs/database/.env
    volumes:
      - pgdata:/var/lib/postgresql
  api:
    image: transcendance-front-end
    build: ./srcs/api
    pull_policy: never
    env_file:
      - ./srcs/api/srcs/.env
    ports:
      - 9090:9090
    restart: always
    depends_on:
      database:
        condition: service_started
    networks:
      - transcendance
    develop:
      watch:
        - path: ./srcs/api/srcs/srcs
          action: sync
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./srcs/api/srcs/package.json
  # website:
  #   build: ./srcs/website
  #   ports:
  #     - "5173:5173"
  #   restart: always
  adminer:
    image: adminer
    restart: always
    networks:
      - transcendance
    ports:
      - 8080:8080

volumes:
  pgdata:

networks:
  transcendance:
    name: transcendance